version: '3'
services:
  #PHP Service
  laravel_graphql_app:
    build:
      context: .
      dockerfile: app.docker
    container_name: laravel_graphql_app
    volumes:
      - ../:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-graphql-network
    links:
      - laravel_graphql_mysql:db
    extra_hosts:
      - host.docker.internal:host-gateway

  #Nginx Service
  web_server:
    image: nginx:1.21.1
    container_name: laravel_graphql_web_server
    ports:
      - 8080:80
    volumes:
      - ../:/var/www
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-graphql-network
    depends_on:
      - laravel_graphql_app

  # MySQL Service
  laravel_graphql_mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33065:3306
    environment:
      MYSQL_DATABASE: laravel_graphql_db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - laravel-graphql-network
    volumes:
      - laravel-graphql-mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

#Docker Networks
networks:
  laravel-graphql-network:
    driver: bridge
volumes:
  laravel-graphql-mysql: {}
